import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { addBookToReading, BookSearchResult, getMyClubs, searchBooks, suggestBook, UserClub } from "../lib/api";
import { AppHeader } from "../components/AppHeader";

export function BookSearchPage() {
  const [params] = useSearchParams(); const [query, setQuery] = useState(""); const [books, setBooks] = useState<BookSearchResult[]>([]); const [error, setError] = useState(""); const [searched, setSearched] = useState(false); const [addingBook, setAddingBook] = useState(""); const [addedBooks, setAddedBooks] = useState<string[]>([]); const [clubs, setClubs] = useState<UserClub[]>([]); const [clubId, setClubId] = useState(params.get("clubId") || ""); const [suggestedBooks, setSuggestedBooks] = useState<string[]>([]);
  useEffect(() => { const token = localStorage.getItem("tomeys_token"); if (token) getMyClubs(token).then(setClubs).catch(() => undefined); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); if (!query.trim()) return; const token = localStorage.getItem("tomeys_token"); if (!token) { setError("Please sign in to search books."); return; } setError(""); setSearched(true); try { setBooks(await searchBooks(query, token)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to search books."); } }
  async function addToReading(book: BookSearchResult) { const token = localStorage.getItem("tomeys_token"); if (!token) { setError("Please sign in to add a book to your reading list."); return; } setError(""); setAddingBook(book.google_books_id); try { await addBookToReading(book.google_books_id, token); setAddedBooks((current) => [...current, book.google_books_id]); } catch (err) { setError(err instanceof Error ? err.message : "Unable to add this book."); } finally { setAddingBook(""); } }
  async function submitSuggestion(book: BookSearchResult) { const token = localStorage.getItem("tomeys_token"); if (!token || !clubId) return; setError(""); setAddingBook(book.google_books_id); try { await suggestBook(Number(clubId), book.google_books_id, token); setSuggestedBooks((current) => [...current, book.google_books_id]); } catch (err) { setError(err instanceof Error ? err.message : "Unable to suggest this book."); } finally { setAddingBook(""); } }
  return <main className="dashboard-page search-page"><AppHeader /><section className="search-hero"><p className="eyebrow">Find your next chapter</p><h1>Search books</h1><form onSubmit={submit}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Title, author, or ISBN" /><button>Search</button></form>{clubs.length > 0 && <label className="suggest-club-select">Suggest search results to a club<select value={clubId} onChange={(event) => setClubId(event.target.value)}><option value="">Choose a club (optional)</option>{clubs.map((club) => <option value={club.id} key={club.id}>{club.name}</option>)}</select></label>}</section>{error && <p className="form-error">{error}</p>}<section className="book-results">{books.map((book) => <article className="book-result" key={book.google_books_id}>{book.thumbnail_url ? <img src={book.thumbnail_url} alt="" /> : <div className="book-cover-fallback">{book.title.charAt(0)}</div>}<div className="book-result-content"><p className="eyebrow">{book.categories || "Book"}</p><h2>{book.title}</h2><p>{book.authors || "Author unknown"}{book.published_date ? ` · ${book.published_date}` : ""}</p>{book.description && <p className="book-description">{book.description}</p>}<div className="book-actions"><button className="add-reading-button" disabled={addingBook === book.google_books_id || addedBooks.includes(book.google_books_id)} onClick={() => addToReading(book)}>{addedBooks.includes(book.google_books_id) ? "Added to your reading" : addingBook === book.google_books_id ? "Adding…" : "Add to my reading"}</button>{clubId && <button className="add-reading-button" disabled={addingBook === book.google_books_id || suggestedBooks.includes(book.google_books_id)} onClick={() => submitSuggestion(book)}>{suggestedBooks.includes(book.google_books_id) ? "Suggested" : addingBook === book.google_books_id ? "Saving…" : "Suggest to club"}</button>}</div></div></article>)}{searched && !books.length && !error && <p className="empty-state">No books matched that search. Try a title or author name.</p>}</section></main>;
}
