import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ClubDiscovery, createClub, discoverClubs, getDashboard, joinClub } from "../lib/api";

export function DiscoverClubsPage() {
  const navigate = useNavigate();
  const [clubs, setClubs] = useState<ClubDiscovery[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [joiningId, setJoiningId] = useState<number | null>(null); const [joined, setJoined] = useState<Record<number, string>>({}); const [memberClubIds, setMemberClubIds] = useState<number[]>([]); const [showCreate, setShowCreate] = useState(false); const [creating, setCreating] = useState(false);
  const search = (value = "") => discoverClubs(value).then(setClubs).catch((err: Error) => setError(err.message));
  useEffect(() => { search(); }, []);
  useEffect(() => { const token = localStorage.getItem("tomeys_token"); if (token) getDashboard(token).then((dashboard) => setMemberClubIds(dashboard.clubs.map((membership) => membership.club.id))).catch(() => undefined); }, []);
  function submit(event: FormEvent) { event.preventDefault(); search(query); }
  async function requestJoin(club: ClubDiscovery) { const token = localStorage.getItem("tomeys_token"); if (!token) { setError("Please sign in to join a club."); return; } setJoiningId(club.id); setError(""); try { const result = await joinClub(club.id, token); setJoined((current) => ({ ...current, [club.id]: result.status ? "Request sent" : "Joined" })); } catch (err) { setError(err instanceof Error ? err.message : "Unable to join this club."); } finally { setJoiningId(null); } }
  async function submitClub(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const token = localStorage.getItem("tomeys_token"); if (!token) { setError("Please sign in to create a club."); return; } const data = new FormData(event.currentTarget); setCreating(true); setError(""); try { const club = await createClub({ name: String(data.get("name")), description: String(data.get("description")), is_public: data.get("visibility") === "public", join_policy: String(data.get("policy")), max_votes_per_user: Number(data.get("votes")) }, token); navigate(`/clubs/${club.id}`); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create this club."); } finally { setCreating(false); } }
  return <main className="dashboard-page search-page"><header className="dashboard-header"><Link className="brand" to="/dashboard">Tomeys</Link><Link className="back-link" to="/dashboard">← Dashboard</Link></header><section className="search-hero"><p className="eyebrow">Find your people</p><h1>Discover book clubs</h1><form onSubmit={submit}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by club name" /><button>Search</button></form><button className="create-club-trigger" onClick={() => setShowCreate((visible) => !visible)}>{showCreate ? "Close creator" : "Create a club"}</button></section>{showCreate && <form className="create-club-form" onSubmit={submitClub}><h2>Start a new chapter</h2><label>Club name<input name="name" required placeholder="The Wednesday Readers" /></label><label>Description<textarea name="description" placeholder="What brings your readers together?" /></label><label>Visibility<select name="visibility" defaultValue="private"><option value="private">Private</option><option value="public">Public</option></select></label><label>Joining<select name="policy" defaultValue="request"><option value="request">Request approval</option><option value="open">Open — anyone can join</option></select></label><label>Votes per member<input name="votes" type="number" min="1" defaultValue="1" /></label><button disabled={creating}>{creating ? "Creating…" : "Create club"}</button></form>}{error ? <p className="form-error">{error}</p> : <section className="result-grid">{clubs.map((club) => <article className="dashboard-card discovery-card" key={club.id}><p className="eyebrow">{club.member_count} readers · {club.join_policy}</p><h2>{club.name}</h2><p>{club.description || "A gathering place for readers."}</p><div className="discovery-actions"><Link className="quiet-link" to={`/clubs/${club.id}`}>Open club →</Link>{!memberClubIds.includes(club.id) && <button className="add-reading-button" disabled={joiningId === club.id || Boolean(joined[club.id])} onClick={() => requestJoin(club)}>{joined[club.id] || (joiningId === club.id ? "Sending…" : club.join_policy === "open" ? "Join club" : "Request to join")}</button>}</div></article>)}{!clubs.length && <p className="empty-state">No clubs matched that search yet.</p>}</section>}</main>;
}
