import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { getDashboard, getReadingEntry, getReadingNotes, saveReadingReview } from "../lib/api";
import { AppHeader } from "../components/AppHeader";

export function ReadingPage() {
  const { readingId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const [entry, setEntry] = useState<any>(location.state?.reading ?? null); const [notes, setNotes] = useState<Array<{ id: number; title: string | null; content: string; created_at: string }>>([]); const [error, setError] = useState(""); const [editingReview, setEditingReview] = useState(false); const [rating, setRating] = useState("75"); const [review, setReview] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const token = localStorage.getItem("tomeys_token"); if (!token || !readingId) { navigate("/auth", { replace: true }); return; } Promise.all([getReadingEntry(readingId, token), getReadingNotes(readingId, token), getDashboard(token)]).then(([reading, noteList, dashboard]) => { const summary = dashboard.history.concat(dashboard.current_readings).find((item) => item.id === Number(readingId)); setEntry({ ...reading, ...summary }); setNotes(noteList); }).catch((err: Error) => setError(err.message)); }, [navigate, readingId]);
  if (error) return <main className="map-page"><section className="auth-content"><h1>That reading is unavailable.</h1><p>{error}</p><Link className="text-link" to="/dashboard">Return to dashboard</Link></section></main>;
  if (!entry) return <main className="map-page"><p className="loading-ink">Opening your reading journal…</p></main>;
  async function saveReview() { const token = localStorage.getItem("tomeys_token"); if (!token || !readingId) return; setSaving(true); try { await saveReadingReview(Number(readingId), Number(rating), review, token); setEntry((current: any) => ({ ...current, rating: Number(rating), review })); setEditingReview(false); } catch (err) { setError(err instanceof Error ? err.message : "Could not save your review."); } finally { setSaving(false); } }
  return <main className="dashboard-page reading-page"><AppHeader /><section className="reading-detail"><p className="eyebrow">Your reading journal</p><h1>{entry.book?.title || "Reading entry"}</h1><p>{entry.book?.authors || ""}</p><div className="detail-rating">{entry.rating !== null && entry.rating !== undefined ? `${entry.rating}/100` : "Not rated yet"}</div><section className="detail-section"><h2>Your review</h2>{editingReview ? <div className="journal-review-form"><label>Rating out of 100<input type="number" min="0" max="100" step="1" value={rating} onChange={(event) => setRating(event.target.value)} /></label><textarea value={review} onChange={(event) => setReview(event.target.value)} placeholder="What stayed with you?" /><button disabled={saving || Number(rating) < 0 || Number(rating) > 100} onClick={saveReview}>{saving ? "Saving…" : "Save rating & review"}</button></div> : <><p>{entry.review || "No review yet."}</p><button className="add-reading-button" onClick={() => { setRating(String(entry.rating ?? 75)); setReview(entry.review || ""); setEditingReview(true); }}>{entry.review ? "Edit rating & review" : "Leave a rating & review"}</button></>}</section><section className="detail-section"><h2>Notes</h2>{notes.length ? notes.map((note) => <article className="journal-note" key={note.id}><time>{new Date(note.created_at).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}</time><p>{note.content}</p></article>) : <p>No notes saved for this book yet.</p>}</section></section></main>;
}
